name: Flutter CI

# This workflow is triggered on pushes to the repository.

on:
  push:
#  pull_request:
#    branches:
#      - master

jobs:
  analyze:
    name: Validate on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        flutter: [ '2.8.0' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ matrix.flutter }}
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter format --set-exit-if-changed .
  build:
    needs: analyze
    name: Build ${{ matrix.build }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ] # path: 'build/app/outputs/apk/release/app-release.apk'
        flutter: [ '2.8.0' ]
        include:
          - os: ubuntu-latest
            build: apk
            path: 'build/app/outputs/apk/release/app-release.apk'
          - os: macos-latest
            build: 'ios --no-codesign'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ matrix.flutter }}
      - run: flutter build ${{ matrix.build }}

#      - name: Firebase App Distribution
#        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.2
#        with:
#          appId: ${{secrets.FIREBASE_APP_ID}}
#          token: ${{secrets.FIREBASE_TOKEN}}
#          groups: testers
#          file: app/build/outputs/apk/release/app-release-unsigned.apk

    - uses: actions/upload-artifact@v1
        with:
          name: release-${{ matrix.build }}
          path: build/app/outputs/apk/release/app-release.apk