name: Flutter CI

# This workflow is triggered on pushes to the repository.

on:
  push:
#  pull_request:
#    branches:
#      - master

jobs:
  analyze:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        flutter: '2.8.0'
        include:
          - os: ubuntu-latest
            build: apk
          - os: windows-latest
            build: apk
          - os: macos-latest
            build: ipa
            args: []
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ matrix.flutter }}
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter format --set-exit-if-changed .
  build:
    - needs: analyze
    - run: flutter build ${{ matrix.build }}
#    - uses: actions/upload-artifact@v1
#        with:
#          name: release-${{ matrix.build }}
#          path: build/app/outputs/apk/release/app-release.apk